allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@oxc-minify/binding-linux-arm64-gnu@0.140.0'
  - '@oxc-minify/binding-linux-x64-gnu@0.140.0'
  - '@oxc-parser/binding-linux-arm64-gnu@0.140.0'
  - '@oxc-parser/binding-linux-x64-gnu@0.140.0'
  - '@oxc-transform/binding-linux-arm64-gnu@0.140.0'
  - '@oxc-transform/binding-linux-x64-gnu@0.140.0'
